### ISSUE TITLE
wswan and ngp (and maybe others) don't show in simplemenu

### ISSUE THREAD

**Issue by plaidman** [eduardofilo/RG350_adam_image#25]
wonderswan and neo geo pocket (and maybe others) don't include .zip extension in their simplemenu configs.

**Comment by eduardofilo** [comment]
Yes, I detected Atari xx00 machines as well. I will check the ones you mention. Thanks...

**Comment by gladel** [comment]
Add .zip in their config ini files under section_groups folder or unzip them from corresponding roms folder.

**Comment by plaidman** [comment]
I did some poking into the RA cores, and it seems like none of the retroarch cores support zip files. I'll continue to poke around and see if I can figure out if it's just a just a core info issue or if zip support is just not built into the cores

**Comment by plaidman** [comment]
turns out - yes, the cores can handle .zip files perfectly well. but the RA core info files don't show .zip as a supported file type. I can make a query with the RA devs and see what they say about it.

**Comment by plaidman** [comment]
I think it's intended behavior. the RA cores don't have to support zip files because RA unzips them before it gets to the core. I was initially looking in an empty folder, so I thought zip files were getting filtered out of the file list, but no, zip files show up in the file browser just fine. I think it's safe to add .zip files to most of the non-cd cores

**Comment by eduardofilo** [comment]
And 7z also in general.

**Comment by eduardofilo** [comment]
Fixed in v1.2

**Comment by gladel** [comment]
@eduardofilo You missed adding zip support for Watara Supervision, too.

**Comment by eduardofilo** [comment]
Really? 🤦‍♂️
I reopen the issue to not lose sight of it.
