### ISSUE TITLE
Blank screen after fresh installation of v2.0 | GCW-Zero

### ISSUE THREAD

**Issue by Tabaluga** [eduardofilo/RG350_adam_image#262]
Dear @eduardofilo ,

thanks for your great effort and the new update.

I've just tried to install the new version 2.0 of the adam image on my GCW-Zero, but I only see a black screen and the system won't start up.

I then reinstalled the old version 1.4.2 as a control. The system boots up as expected and everything runs without problems.

Thanks again for your hard effort.

Best regards

**Comment by eduardofilo** [comment]
Sorry to hear that. Thanks for the warning. Do me a favor if you don't mind, please. Flash the image v2.0 normally and then instead of running the script to select the kernel, manually copy the two files inside this zip to the root of the boot partition of the card you just flashed. Then try to boot.

[uzImage.zip](https://github.com/eduardofilo/RG350_adam_image/files/8987343/uzImage.zip)

**Comment by Tabaluga** [comment]
Dear @eduardofilo ,

flashed as instructed with the two files from the zip file to the root of the boot partition of the sd-card.

Still a black screen and the system won't start up.

Thanks again for your hard effort.

Best regards

**Comment by eduardofilo** [comment]
OK, so it looks like it's the bootloader. It is more difficult to give you instructions on how to test. I'll think of something. Thanks for testing it.

**Comment by rkoll927** [comment]
I am having the same issues as Tabaluga except on the PocketGo2 v1.  I rolled back to 1.4.2 without issue.  I didn't try the kernel files linked above, assuming they are for the GCW-Zero. 

Thank you for your dedication to this project.  This is definitely the best CFW I've used on the PG2 v1.

**Comment by eduardofilo** [comment]
This seems to confirm that it is a bootloader problem. When I have time I will build a version of Adam v2.0 with the bootloader of your machines that was in v1.4.2 for you to test. Thank you.

**Comment by nicahokie** [comment]
I think this issue is caused by this OpenDingux Issue: https://github.com/OpenDingux/buildroot/issues/77
@pcercuei is aware of the issue but needs to find time to work on it.

**Comment by eduardofilo** [comment]
Could you please try this new version to see if it boots?

https://drive.google.com/file/d/1ayiZAxU93RZnl2g-X56vtUkHiUYX6aVL/view?usp=sharing

**Comment by nicahokie** [comment]
Thank you for your attention to this issue.
On my GCW Zero it boots to a blank screen and I did not forget to run select_kernel.

**Comment by eduardofilo** [comment]
And v1.4.2 worked fine?

**Comment by nicahokie** [comment]
I was about to say that on my unit 1.4.2 does not work either - blank screen as well...  Only older OD Betas or Stock OD do not have the blank screen issue for me.
So perhaps the beta build > v2.0 might still help others where 1.4.2 does work for them but not = v2.0.

**Comment by rkoll927** [comment]
Just tried the image you provided.  Unfortunately, it did not boot on the PG2 v1.  I reverted back to 1.4.2, it boots up and everything seems to work fine.  

In the interest of eliminating a dud SD as a variable, I tried with a few different cards on my PC and a mac.  All 2.0.1 were non-booting and all 1.4.2 booted.

Thanks for you hard work.

**Comment by piklz** [comment]
280v bootloop on opendingux screen logo for anyone? on v2 image?

**Comment by eduardofilo** [comment]
I think I have found it. There was indeed something wrong with the part that builds the image for GCW-Zero and PocketGo2v1. It was a silent bug that should be fixed by now. Please test this new version on your machines.

https://drive.google.com/file/d/1FW3rlCHbDK7WvBrdoxSdlyav7siNH0mT/view?usp=sharing

**Comment by nicahokie** [comment]
Thank you very much for your efforts. On my GCW Zero I still get a blank screen.

**Comment by eduardofilo** [comment]
But in your case 1.4.2 no worked yet, so it could be an isolated case. I need someone who worked 1.4.2 but not 2.0 to test if this 2.0.1b works now.
Thanks.

**Comment by rkoll927** [comment]
I just  flashed 2.0.1b.  Booted right up on the PG2 v1. Played through a few levels on a number of different systems, all working well.  

Thanks you for your had work on squashing that bug!

**Comment by eduardofilo** [comment]
OK, in that case I will maintain support for those consoles. Thank you for testing it.

**Comment by eduardofilo** [comment]
v2.1 created.
It should boot into GCW-Zero and PocketGo2v1.
