### ISSUE TITLE
REQUEST: Image works on PocketGo2/PlayGo Rev2 devices already, please add Rev1 support

### ISSUE THREAD

**Issue by esmith13** [eduardofilo/RG350_adam_image#7]
The PocketGo2 (also sold as the PlayGo) had two hardware revisions. The difference being (I believe) that Rev2 added a reset button and has a different screen driver. The most common firmware for both revisions is Rogue CFW and the only difference between getting the firmware to work on each revision is their version of the boot files that your setup script changes when you choose which device your running on. Rev 2 devices work with your current boot files for the RG350, but Rev 1 devices won't work with any of the available options. Would it be possible for you to add support for the Rev 1 devices? Here is a link to that CFW for reference if it helps:   https://github.com/Ninoh-FOX/POCKETGO2_ROGUE_CFW

Thanks in advance for your time and your image is AMAZING work! My 280V and I thank you!

**Comment by eduardofilo** [comment]
The PlayGo (PocketGo2 Rev1) support is prepared yet in the future v1.0.4 revision of the image. In one or two days I will release it.

Thanks to you.

**Comment by esmith13** [comment]
Thank you so much!

**Comment by eduardofilo** [comment]
Can you do me a favor?
Someone with PlayGo/PG2 v1 please, flash this image. I suppose that this one will boot, but will show the screen problems like the @NickMellon video.
I would also like you to try on the GCW0 if any of you have it. To finish understanding if GCW0 and PlayGo/PG2 v1 are compatible at the bootloader and device tree level.

https://drive.google.com/file/d/1-p6u9pWBqrO99TqU3DgPW-7ysY6k-LD1/view?usp=sharing

**Comment by NickMellon** [comment]
Can someone else try to confirm I'm not an idiot? I get no LEDs and a black screen on my PG2v1 using the above image.

**Comment by MartianMSK** [comment]
> Can someone else try to confirm I'm not an idiot? I get no LEDs and a black screen on my PG2v1 using the above image.

I don't have it with me. I'll try it tomorrow.

**Comment by eduardofilo** [comment]
@NickMellon Surely you have done well. It is difficult to prepare the image by touching files blindly.

**Comment by eduardofilo** [comment]
Someone with a GCW0?

**Comment by slinky70** [comment]
this test image also doesn't work for me on my pg2v1....i don't have gcw0...sorry

**Comment by Ninoh-FOX** [comment]
> this test image also doesn't work for me on my pg2v1....i don't have gcw0...sorry

This is normal, not is the same screen driver

**Comment by eduardofilo** [comment]
I am going to add a new test to the request. So in summary:

1. Test this on PlayGo / PG2 v1 https://drive.google.com/file/d/1-p6u9pWBqrO99TqU3DgPW-7ysY6k-LD1/view?usp=sharing
2. Test this on GCW0 https://drive.google.com/file/d/1-p6u9pWBqrO99TqU3DgPW-7ysY6k-LD1/view?usp=sharing
3. Test normal Adam on PlayGo / PG2 v2 selecting kernel `5: PlayGo / PocketGo2 v1`, **not** the `3: RG350/P / PocketGo2 v2`

Test 1 have been made by @NickMellon and @slinky70 and I think we can consider it enough tried.

**Comment by eduardofilo** [comment]
One more request. Can anyone with PlayGo/PG v1 and v2 send me the content of file `/proc/cmdline`?
You can view it with Dingux Cmdr or make a cat by SSH. This is the result in a RG280V for example:

```
rg280v:~ $ cat /proc/cmdline
mem=0x0100M mem=0x0100M@0x30000000 root=/dev/loop0 root=/dev/mmcblk0p1 rootfstype=vfat rootwait ro init=/sbin/init init=/mininit-syspart console=ttyS2,57600 earlycon console=tty0 splash rfkill.default_state=0 -- hwvariant=rg350  
```

Ideally on stock firmware. And if you do, please tell if it is a v1 or v2 device.

**Comment by ClaireSoftware** [comment]
Both the normal adam setup and the PG2v1 test image don't work on my PG2v1, just to be another confirmation.

**Comment by ClaireSoftware** [comment]
these are the contents of /proc/cmdline on my pg2v1. 
``
mem=0x0100M mem=0x0100M@0x30000000 root=/dev/loop0 root=/dev/mmcblk0p1 rootfstype=vfat rootwait ro init=/sbin/init init=/minit-syspart console=tty0 fbcon=bind:0 rfkill.default_state=0 -- hwvariant=v20_mddr_512mb panic=5 console=tty52,57600 console=tty0 boot=/dev/mmcblk0p1 loop0=/boot/rootfs.squashfs root=/dev/loop0 rfkill.default_state=0
``

**Comment by eduardofilo** [comment]
Than you very much. That confirms that PG2 v1 is identified as GCW0 in the ODBeta updater.

Can someone with PG2 v2 do the same test?

**Comment by retrogamecorps** [comment]
Here is the PlayGo v2 (copied by hand, forgive any typos!):

`mem=0x0100M mem-0x0100Mx0x3000000 root=/dev/mmcblk0p1 rootfstype-vfat rootwait ro init=mininit-syspart console=tty0 fbcon=bind:0 rfkill.default_state=0 -- hwvariant=rg350 panic=5 console=ttyS2,57600 console=tty- boot=/dev/mmcblk0p1 loop0=/boot/rootfs.squashfs root=/dev/loop0 rfkill.default_state=0`

**Comment by eduardofilo** [comment]
Thanks to this data I have been able to follow the steps of the ODBeta update script and now I am sure that the device tree for playgo corresponds to v2, and not v1 as I initially assumed. On the other hand, the PlayGo v1 I have already seen that it is identified in that script as "gcw0". Although it is not worth supporting that version of the console because ODBeta does not work well on it yet (the screen looks bad).
Thank you all.

**Comment by pcercuei** [comment]
@eduardofilo I'd suggest to only support the devices that are officially supported by OD beta; and if you want to add support for a new device, add it to OD beta first.

**Comment by eduardofilo** [comment]
@pcercuei It was precisely just a confusion about the devices supported in ODBeta. I will try not to make it happen again.

**Comment by pcercuei** [comment]
The Playgo (aka. PocketGo2 v2) should already be supported by OD beta. The PocketGo v1 and the PocketGo2 v1 aren't officially supported (mostly because I don't have any of those).

If the PocketGo v1 is so similar to the GCW-Zero, is the PocketGo v1 working correctly when flashed with the GCW-Zero device tree?

**Comment by Ninoh-FOX** [comment]
> The Playgo (aka. PocketGo2 v2) should already be supported by OD beta. The PocketGo v1 and the PocketGo2 v1 aren't officially supported (mostly because I don't have any of those).
> 
> If the PocketGo v1 is so similar to the GCW-Zero, is the PocketGo v1 working correctly when flashed with the GCW-Zero device tree?

The screen not work and you need remaped some keys. But all other yes work.

**Comment by esmith13** [comment]
PlayGo has both hardware revisions just like PocketGo2. My PlayGo is Rev1 hardware and will NOT work correctly with ODBeta and your image will not boot at all. Results are identical to posted video. PlayGo Rev1 has no reset button and PlayGo rev2 DOES have a reset button. The only difference between PlayGo and PocketGov2 is plastic shell and name.

**Comment by pcercuei** [comment]
@esmith13 so: PocketGo2 v1 == PlayGo v1, and PocketGo v2 == PlayGo v2?

**Comment by esmith13** [comment]
PocketGo2 Rev1 == PlayGo Rev1, and PocketGo2 Rev2 == PlayGo Rev2
The difference is if the device has a reset button on the lower left. 
No reset button == Rev1 == GCW0 profile
Has reset button == Rev2 == RG350 profile

**Comment by pcercuei** [comment]
@esmith13 alright thanks.

**Comment by pcercuei** [comment]
@esmith13 one last question, since you seem to know your topic - any of these have a real analog stick? Or they are hardwired to the dpad?

**Comment by esmith13** [comment]
it has a tru analog input but it is a slider, like nintendo 3dS or right side analog of retroid pocket 2.

**Comment by pcercuei** [comment]
All of them?

**Comment by esmith13** [comment]
I only have a Rev1 PocketGo2 and Rev 1 PlayGo.
I do not have a Rev2 of either device but I cannot imagine they reduced functionality on the newer revision.

**Comment by esmith13** [comment]
internal pics of both Rev1 devices. Note analog input in lower right and board version in upper left (GCWZERO_V1.2  2019.11.26)

**Comment by Ninoh-FOX** [comment]
> @esmith13 one last question, since you seem to know your topic - any of these have a real analog stick? Or they are hardwired to the dpad?

The stick work fine with the GCW0 configurarion.

**Comment by esmith13** [comment]
Only problem with GCW0 version I can see is the garbled spinach green graphics.

**Comment by Ninoh-FOX** [comment]
Yes, I am make a dts with the rest buttons in PG2v1, and all work fine, only rest fix the screen drivers

**Comment by pcercuei** [comment]
I think this DTS should work on the PG2 Rev1, along with `ubiboot-v20_mddr_512mb.bin`:
```
// SPDX-License-Identifier: GPL-2.0
/dts-v1/;

#include "playgo.dts"

/ {
	compatible = "wolsen,pocketgo2", "ingenic,jz4770";
	model = "Wolsen PocketGo 2";
};

&btn8 {
	gpios = <&gpb 20 GPIO_ACTIVE_LOW>;
};

&btn_l2 {
	gpios = <&gpd 31 GPIO_ACTIVE_LOW>;
};

&btn_r2 {
	gpios = <&gpf 10 GPIO_ACTIVE_LOW>;
};

&btn_volp {
	gpios = <&gpd 19 GPIO_ACTIVE_LOW>;
};

&btn_volm {
	gpios = <&gpe 13 GPIO_ACTIVE_LOW>;
};

&gpio_keys {
	button@17 {
		label = "Menu button";
		linux,code = <KEY_HOME>;
		linux,can-disable;
		gpios = <&gpe 8 GPIO_ACTIVE_LOW>;
	};
};
```

**Comment by pcercuei** [comment]
Could somebody give me the result of `uname -a` on all PocketGo / PlayGo devices?

**Comment by esmith13** [comment]
how can i run commands on the device? I can do it for both Rev1 devices if you can explain how to ssh in from a windows pc or run directly on device

**Comment by pcercuei** [comment]
@esmith13 in Windows 10: plug the device to USB, open a windows console, and run `ssh root@10.1.1.2`.

**Comment by esmith13** [comment]
PocketGo2 Rev1:     Linux opendingux 3.12.0-dingux #35 Thu Sep 26 23:15:49 CST 2019 mips GNU/Linux
PlayGo Rev1:           Linux opendingux 3.12.0-dingux #35 Thu Sep 26 23:15:49 CST 2019 mips GNU/Linux

**Comment by pcercuei** [comment]
@esmith13 could you try to update one of these to OD beta with this OPK: https://app.box.com/s/18xteue71ol80s4ipl30be8vmrfrf3ji

Only do it if you are okay with losing your data, if it doesn't work you'll probably need a reflash.

**Comment by esmith13** [comment]
no worries. using new/spare SD cards for all of this testing.
running on PocketGo2 rev1 now, I can do separately on PlayGo as well if you would feel better seeing both, although I truly believe they are 100% identical hardware

**Comment by esmith13** [comment]
Exact same spinach green graphical mess using the 21.8.30 as with the 21.8.25 version on PocketGo2 Rev1
Do you want me to update the PlayGo as well?

**Comment by pcercuei** [comment]
@esmith13 if you SSH now (`ssh od@10.1.1.2`, you might have to set passwordless login in the "password" app first...), and run `cat /proc/cpuinfo` it should print a line with `machine : Wolsen PocketGo2`, correct?

**Comment by esmith13** [comment]
is there a shortcut key to launch the network tool? I cannot see with the garbled graphics to enable the network on the device

**Comment by pcercuei** [comment]
I think I screwed up and it didn't detect it properly. I uploaded a new OPK (same URL), could you try again with the new one?

**Comment by esmith13** [comment]
of course. need a few minutes to reflash stock then update.

**Comment by Ninoh-FOX** [comment]
> I think this DTS should work on the PG2 Rev1, along with `ubiboot-v20_mddr_512mb.bin`:
> 
> ```
> // SPDX-License-Identifier: GPL-2.0
> /dts-v1/;
> 
> #include "playgo.dts"
> 
> / {
> 	compatible = "wolsen,pocketgo2", "ingenic,jz4770";
> 	model = "Wolsen PocketGo 2";
> };
> 
> &btn8 {
> 	gpios = <&gpb 20 GPIO_ACTIVE_LOW>;
> };
> 
> &btn_l2 {
> 	gpios = <&gpd 31 GPIO_ACTIVE_LOW>;
> };
> 
> &btn_r2 {
> 	gpios = <&gpf 10 GPIO_ACTIVE_LOW>;
> };
> 
> &btn_volp {
> 	gpios = <&gpd 19 GPIO_ACTIVE_LOW>;
> };
> 
> &btn_volm {
> 	gpios = <&gpe 13 GPIO_ACTIVE_LOW>;
> };
> 
> &gpio_keys {
> 	button@17 {
> 		label = "Menu button";
> 		linux,code = <KEY_HOME>;
> 		linux,can-disable;
> 		gpios = <&gpe 8 GPIO_ACTIVE_LOW>;
> 	};
> };
> ```

Think that PG2v1 and PG2v2 has differents id keys in R2 and L2. You need redefined this too.

**Comment by esmith13** [comment]
@pcercuei 2nd test was mostly successful. Graphics are completely fixed. 1st boot hung at 66% (right edge of square logo) for about 4 minutes and then completed. NO buttons work at all, nor does DPad. Analog slider works fine.
Results are 100% identical on both PocketGo2 Rev1 and PlayGo Rev1 - I have updated both independently of each other (seperate SD cards, no sharing)

**Comment by pcercuei** [comment]
> Think that PG2v1 and PG2v2 has differents id keys in R2 and L2. You need redefined this too.

This is only for PG2v1. PG2v2 is already supported in OD beta.

**Comment by esmith13** [comment]
Analog slider is also rotated 90 degrees clockwise.
sliding right moves down, sliding down moves left, etc.

**Comment by Ninoh-FOX** [comment]
> > Think that PG2v1 and PG2v2 has differents id keys in R2 and L2. You need redefined this too.
> 
> This is only for PG2v1. PG2v2 is already supported in OD beta.

I talk about PG2v1, the R2 and L2 id is:

button@13 {
		label = "L2 shoulder button";
		linux,code = <KEY_RIGHTSHIFT>;
		linux,can-disable;
		gpios = <&gpd 31 GPIO_ACTIVE_LOW>;
	};

	button@14 {
		label = "R2 shoulder button";
		linux,code = <KEY_RIGHTALT>;
		linux,can-disable;
		gpios = <&gpf 10 GPIO_ACTIVE_LOW>;
	};

**Comment by pcercuei** [comment]
I used PD31 and PF10 for L2/R2 too.

**Comment by Ninoh-FOX** [comment]
then the linux,code not is nessesary?

**Comment by pcercuei** [comment]
These two buttons are already defined in rg280v.dts, so we only need to override things that changed - aka the GPIOs.

**Comment by Ninoh-FOX** [comment]
oh, I see, this fixed then the problems with retroarch

**Comment by Ninoh-FOX** [comment]
I am make a new dts and now all work fine... I think my stuck in this has been not doing clean installs in each test, now everything works correctly

```// SPDX-License-Identifier: GPL-2.0
/dts-v1/;

#include "gcw0.dts"

/ {
	compatible = "wolsen,PocketGo2", "ingenic,jz4770";
	model = "wolsen PocketGo2";
	
	panel {
		compatible = "frida,frd350h54004";

		reset-gpios = <&gpe 2 GPIO_ACTIVE_LOW>;

		backlight = <&backlight>;
		power-supply = <&vcc>;

		port {
			frida_input: endpoint {
				remote-endpoint = <&panel_output>;
			};
		};
	};
};

&pins_lcd {
	groups = "lcd-24bit";
};

&panel {
	status = "disabled";
};

/* Make ABT panel port a dummy to avoid DTC complaints */
&panel_input {
	remote-endpoint = <&panel_input>;
};

&panel_output {
	remote-endpoint = <&frida_input>;
};

&btn6 {
	label = "Button X";
};

&btn7 {
	label = "Button Y";
};
&btn8 {
	gpios = <&gpb 20 GPIO_ACTIVE_LOW>;
};

&btn9 {
	gpios = <&gpe 26 GPIO_ACTIVE_LOW>;
};

&pmu {
	charger = <&usb_conn>;
	power-supplies = <&usb_conn>;
};

&usb_conn {
	vbus-supply = <&vcc>;
};

&gpio_keys {
		button@14 {
			label = "L2 shoulder button";
			linux,code = <KEY_PAGEUP>;
			linux,can-disable;
			gpios = <&gpd 31 GPIO_ACTIVE_LOW>;
		};

		button@15 {
			label = "R2 shoulder button";
			linux,code = <KEY_PAGEDOWN>;
			linux,can-disable;
			gpios = <&gpf 10 GPIO_ACTIVE_LOW>;
		};
	
		button@16 {
			label = "Volume+ button";
			linux,code = <KEY_VOLUMEUP>;
			linux,can-disable;
			gpios = <&gpd 19 GPIO_ACTIVE_LOW>;
		};

		button@17 {
			label = "Volume- button";
			linux,code = <KEY_VOLUMEDOWN>;
			linux,can-disable;
			gpios = <&gpe 13 GPIO_ACTIVE_LOW>;
		};
	
		button@18 {
			label = "Menu button";
			linux,code = <KEY_RIGHTCTRL>;
			linux,can-disable;
			gpios = <&gpe 8 GPIO_ACTIVE_LOW>;
		};
};

&i2c4 {
	status = "disabled";
};

&it6610 {
	status = "disabled";
};

&dc_charger {
	status = "disabled";
};

&i2c0 {
	status = "disabled";
};

&radio {
	status = "disabled";
};

&usb_vbus {
	status = "disabled";
};
```

**Comment by pcercuei** [comment]
@Ninoh-FOX could you please set the password setting to "connect without password", then boot with my DTS, and give me the output of `dmesg`?

**Comment by pcercuei** [comment]
@esmith13 Is the analog stick clickable?

**Comment by esmith13** [comment]
no. is is a slider, not a stick. there is no click/button input

**Comment by Ninoh-FOX** [comment]
> @Ninoh-FOX could you please set the password setting to "connect without password" and USB mode to Ethernet, then boot with my DTS, and give me the output of `dmesg`?

Sure a second

**Comment by pcercuei** [comment]
@Ninoh-FOX That's not my DTS :) I need the dmesg with my DTS.

**Comment by Ninoh-FOX** [comment]
> @Ninoh-FOX That's not my DTS :) I need the dmesg with my DTS.

ops, but this works all...

this is the kernel file

https://mega.nz/file/v0hmEZKa#OAL1EeWN0WBnhzEnNZYqCzjO7q4YoeCEY6zVfblu60g

**Comment by pcercuei** [comment]
I know, I just need to understand why gpio-keys fail with mine.

**Comment by esmith13** [comment]
@Ninoh-FOX FYI, your mega link has a corrupt .7z file. won't open with either 7z or WinRAR.

**Comment by Ninoh-FOX** [comment]
> @Ninoh-FOX FYI, your mega link has a corrupt .7z file. won't open with either 7z or WinRAR.

that is true, true this.
https://mega.nz/file/apwUgTSa#3i3Ro7AJfkNPuJQtjlSKCFt3y2-gIEMfkYpl356GsEE

@pcercuei I tried your dts after, but not work fine, I remember that in 3.12 some gpios brocken the controls, I am use my platform-gcw0.c how way for make the dts, and I am used gcw0 direct because I know that has the same stick control that PG2v1.

If you need this, I can rebuild the kernel with your dts.

**Comment by pcercuei** [comment]
I know it's broken, I just need to see the dmesg.

**Comment by Ninoh-FOX** [comment]
a second

**Comment by Ninoh-FOX** [comment]
the error with your dts is:
```
[    1.793525] gpio-keys gpio-keys: failed to get gpio: -16
[    1.803045] gpio-keys: probe of gpio-keys failed with error -16
```

**Comment by Ninoh-FOX** [comment]
> > @Ninoh-FOX FYI, your mega link has a corrupt .7z file. won't open with either 7z or WinRAR.
> 
> that is true, try this.
> https://mega.nz/file/apwUgTSa#3i3Ro7AJfkNPuJQtjlSKCFt3y2-gIEMfkYpl356GsEE
> 
@esmith13 work the files in zip in your console?

**Comment by esmith13** [comment]
Contents are different that the fat partition for stock/ODBeta image so I wasn't sure how to try them?

**Comment by esmith13** [comment]
> Can you do me a favor?
> Someone with PlayGo/PG2 v1 please, flash this image. I suppose that this one will boot, but will show the screen problems like the @NickMellon video.
> I would also like you to try on the GCW0 if any of you have it. To finish understanding if GCW0 and PlayGo/PG2 v1 are compatible at the bootloader and device tree level.
> 
> https://drive.google.com/file/d/1-p6u9pWBqrO99TqU3DgPW-7ysY6k-LD1/view?usp=sharing

Can also confirm this does NOT boot at all. (sorry for the delay, missed this over the weekend)
So, does this decisively mean there will be no Adam Image for PocketGo2 v1/PlayGo v1 or is there a way I or someone else can make this happen?

**Comment by esmith13** [comment]
@eduardofilo the files provided by @Ninoh-FOX fix ODBeta completely on both of those devices. I now have a fully functional ODBeta on both of my Rev 1 devices. Current required process is:
1) Stock FW flash
2) ODBeta .opk update
3) replace boot files on FAT partition with those provided by @Ninoh-FOX

**Comment by pcercuei** [comment]
Or just wait until it lands in OD nightly.

**Comment by eduardofilo** [comment]
Very good news. But better to wait for the changes to be integrated upstream.
Meanwhile you can apply that same step 3 after flashing the image if you want to use it.

**Comment by esmith13** [comment]
my apologies, i didn't know it was getting officially added eventually. I can wait as long as needed. Just wasn't sure if it would eventually happen or NEVER happen... Thank you to all for the help and support!

**Comment by eduardofilo** [comment]
No, no. Thank you to you for helping in the research.

**Comment by pcercuei** [comment]
Does PocketGo2 / PlayGo Rev. 2 have HDMI, btw?

**Comment by esmith13** [comment]
no. only additional feature from Rev1 to Rev2 is a reset button.

**Comment by pcercuei** [comment]
Thanks. I should have PocketGo2 / PlayGo Rev. 1/2 support in OD beta in today's nightly build.

**Comment by Ninoh-FOX** [comment]
@pcercuei PG2v1 and PG2v2 not has hdmi, nos has too otg usb port (has in the chip, but not fisical port).

PG2v1 not has rumble.

**Comment by ClaireSoftware** [comment]
> 
> 
> Contents are different than the fat partition for stock/ODBeta image so I wasn't sure how to try them?
> 
> EDIT: copied over files to my ODBeta SD card, including overwriting the four files that were named the same and adding new files. Worked great! All inputs registered properly. Tried on both PocketGo2 Rev1 & PlayGo Rev1 with same excellent results on both.
> This is now a fully functional ODBeta install on both Rev1 devices.

Out of curiosity, does this ODbeta build support the super mario 64 beta. I know rogue CFW got it to working sound but graphical glitches. Does the beta build you have get rid of said glitches?

**Comment by esmith13** [comment]
@ClaireSoftware link me to a GCW0 compatible build and I'd be happy to try for you.

**Comment by ClaireSoftware** [comment]
> 
> 
> @ClaireSoftware link me to a GCW0 compatible build and I'd be happy to try for you.

do you have an e-mail address, discord, or the like? since it's got nintendo IP in it, I can't just post a build. there's a google code link to building it yourself if you have a mario 64 ROM.

**Comment by esmith13** [comment]
> > @ClaireSoftware link me to a GCW0 compatible build and I'd be happy to try for you.
> 
> do you have an e-mail address, discord, or the like? since it's got nintendo IP in it, I can't just post a build. there's a google code link to building it yourself if you have a mario 64 ROM.

discord:  esmith13#7028
email:  esmith13@gmail.com

**Comment by Ninoh-FOX** [comment]
> > Contents are different than the fat partition for stock/ODBeta image so I wasn't sure how to try them?
> > EDIT: copied over files to my ODBeta SD card, including overwriting the four files that were named the same and adding new files. Worked great! All inputs registered properly. Tried on both PocketGo2 Rev1 & PlayGo Rev1 with same excellent results on both.
> > This is now a fully functional ODBeta install on both Rev1 devices.
> 
> Out of curiosity, does this ODbeta build support the super mario 64 beta. I know rogue CFW got it to working sound but graphical glitches. Does the beta build you have get rid of said glitches? @esmith13

SM64port MAY works, this not is a ROGUE version. It is OD beta. XD

**Comment by esmith13** [comment]
FYI to anyone interested - SM64 port works flawlessly on this hodge-podge ODBeta for PG2v1. Quite impressive, actually.

**Comment by pcercuei** [comment]
@esmith13 PocketGo2/PlayGo Rev. 1 & 2 are now supported officially in OpenDingux beta starting from the next nightly build.

It would be great if you can test. The build will be ready in a few hours, at this address: http://od.abstraction.se/opendingux/latest/

**Comment by esmith13** [comment]
Will do.

**Comment by esmith13** [comment]
> @esmith13 PocketGo2/PlayGo Rev. 1 & 2 are now supported officially in OpenDingux beta starting from the next nightly build.
> 
> It would be great if you can test. The build will be ready in a few hours, at this address: http://od.abstraction.se/opendingux/latest/

Works perfectly on both Rev1 devices! 
Even fully performs shutdown (the hodge-podge setup rebooted when you pressed shutdown)

Not that I expect anything to work differently, but I will now try nightly retroarch for ODBeta and SM64 port.
I'll edit this post with those results later.

Thanks @pcercuei for the quick turn around!

**Comment by esmith13** [comment]
I stand corrected. It only shutdown correctly the first time. On subsequent uses, choosing "power off" from settings does exactly the same thing as "reboot".

**Comment by pcercuei** [comment]
At least now you have a true suspend mode while I fix the issue :D

**Comment by esmith13** [comment]
Do you mean POWER + Y ?
That does work!

**Comment by Ninoh-FOX** [comment]
> I stand corrected. It only shutdown correctly the first time. On subsequent uses, choosing "power off" from settings does exactly the same thing as "reboot".

This is for the rtc driver, need a diferent config that the other consoles modes or the console always reboot.

I think that this don't happe with my dts.

**Comment by esmith13** [comment]
I did. As a matter of fact removing the battery is the only way to fully shutdown right now, so I have removed the battery, reinserted it, used the device, tried to shutdown unsuccessfully and then removed the battery and started the cycle again over a dozen times at this point. it always reboots instead of shutting down now.

**Comment by Ninoh-FOX** [comment]
> I did. As a matter of fact removing the battery is the only way to fully shutdown right now, so I have removed the battery, reinserted it, used the device, tried to shutdown unsuccessfully and then removed the battery and started the cycle again over a dozen times at this point. it always reboots instead of shutting down now.
> 
> EDIT: HAH! RTC was the key!! I used the clock app to set the correct date/time and now the device shuts down correctly! It was originally set to a date far in the future, The year was 2036.

I said that the problem was the RTC (real time clock) ;)

I don't have the reboot problem in my tests (I don't test the last nightly), but is nice know that is fixed.

**Comment by esmith13** [comment]
> I said that the problem was the RTC (real time clock) ;)
I know. your saying that is why I tried setting the clock.
Thank you!

**Comment by pcercuei** [comment]
@esmith13 is the analog stick working fine?

**Comment by esmith13** [comment]
yes. all directions are correct and retroarch for ODBeta sees it as an actual analog input.

**Comment by esmith13** [comment]
odd... after a few more power cycles it is no longer shutting down again. Date/Time had again reset to the year 2036.
I pulled battery, reset Date/Time correctly, and tried to shutdown again and it still will only reboot.
It originally worked correctly for a couple hours and a 5-7 shutdowns. Guess there is still an RTC issue to be resolved in software?

**Comment by ClaireSoftware** [comment]
Yeah, for me, the analogue stick isn't working on my pg2v1, but only specifically on the odbeta August 31st nightly. On the 25th nightly installed with ninoh-fox's boot partition, the analogue stick works fine. On stock, the analogue stick works fine. On rogue CFW, the analogue stick works fine. Using a hardware tester app, I'm not getting any inputs, so it seems to not be bound to anything at all.

**Comment by esmith13** [comment]
i'm gonna flash again and start from scratch. perhaps i confused my sd cards between the hodge-podge and the 21.8.31 nightly ODBeta...

**Comment by Ninoh-FOX** [comment]
> Yeah, for me, the analogue stick isn't working on my pg2v1, but only specifically on the odbeta August 31st nightly. On the 25th nightly installed with ninoh-fox's boot partition, the analogue stick works fine. On stock, the analogue stick works fine. On rogue CFW, the analogue stick works fine. Using a hardware tester app, I'm not getting any inputs, so it seems to not be bound to anything at all.

Try this tester https://github.com/RafaVico/pg2_test/blob/master/pg2test.opk

**Comment by ClaireSoftware** [comment]
So far, it seems like both the power and menu buttons are recognized as 0x0116 (SDLK_HOME) and the analogue stick is simply not detected (on official ODbeta on top of stock). Shoulder buttons are detected as SDLK_PAGEUP and SDLK_PAGEDOWN.

**Comment by esmith13** [comment]
agree with @ClaireSoftware . I confused my SD cards.
No analog function. Agree with his other comments too but to be more specific: L2=PageUp but not identified as L2, R2=PageDown but not identified as R2, Menu=Home and is identified as power button. all other buttons identify correctly, including actual power button.

**Comment by Ninoh-FOX** [comment]
PageDown and PageUp it is correct (i don't has time for update the tester) the stick work fine if you use the dts from GCW0 how base ( In my test imagen system work, the Mega 7zip file)

**Comment by esmith13** [comment]
yes yours does, but @pcercuei wanted to know if his 21.8.31 nightly fixed it in ODBeta itself, which apparently it did not.

**Comment by pcercuei** [comment]
@esmith13 could you run `dmesg` on the device over SSH/telnet?

**Comment by esmith13** [comment]
sure. will update this post in a few min with results.

**Comment by pcercuei** [comment]
The joystick driver is properly loaded:
`[    1.732366] input: joystick as /devices/platform/joystick/input/input0`

**Comment by esmith13** [comment]
joystick does not function in gmenu2x, nor retroarch, nor the pg2test_pg2v2.opk. It does function in all of those places using @Ninoh-FOX files in the FAT partition.
anything else I can check for you to help?

**Comment by pcercuei** [comment]
Could you run (as root) on both Ninoh's files and latest OD nightly:
`cat /sys/kernel/debug/gpio`

**Comment by esmith13** [comment]
what is root password? i'm logged in as 'od'

**Comment by esmith13** [comment]
your 21.8.31 image

```
pocketgo2:/ $ sudo cat /sys/kernel/debug/gpio
gpiochip0: GPIOs 0-31, parent: platform/10010000.pin-controller, GPIOA:
 gpio-30  (                    |Power button        ) in  hi IRQ ACTIVE LOW

gpiochip1: GPIOs 32-63, parent: platform/10010000.pin-controller, GPIOB:
 gpio-34  (                    |cd                  ) in  lo IRQ ACTIVE LOW
 gpio-37  (                    |vbus                ) in  hi IRQ
 gpio-52  (                    |Left shoulder button) in  hi IRQ ACTIVE LOW
 gpio-53  (                    |Start button        ) in  hi IRQ ACTIVE LOW
 gpio-62  (                    |power               ) out lo ACTIVE LOW

gpiochip2: GPIOs 64-95, parent: platform/10010000.pin-controller, GPIOC:

gpiochip3: GPIOs 96-127, parent: platform/10010000.pin-controller, GPIOD:
 gpio-114 (                    |Select button       ) in  lo IRQ
 gpio-115 (                    |Volume+ button      ) in  hi IRQ ACTIVE LOW
 gpio-127 (                    |L2 shoulder button  ) in  hi IRQ ACTIVE LOW

gpiochip4: GPIOs 128-159, parent: platform/10010000.pin-controller, GPIOE:
 gpio-136 (                    |Menu button         ) in  hi IRQ ACTIVE LOW
 gpio-137 (                    |regulator@1         ) out lo ACTIVE LOW
 gpio-141 (                    |Volume- button      ) in  hi IRQ ACTIVE LOW
 gpio-148 (                    |Button B            ) in  hi IRQ ACTIVE LOW
 gpio-149 (                    |D-pad up            ) in  hi IRQ ACTIVE LOW
 gpio-151 (                    |D-pad left          ) in  hi IRQ ACTIVE LOW
 gpio-152 (                    |D-pad right         ) in  hi IRQ ACTIVE LOW
 gpio-153 (                    |D-pad down          ) in  hi IRQ ACTIVE LOW
 gpio-154 (                    |Right shoulder butto) in  hi IRQ ACTIVE LOW
 gpio-155 (                    |Button X            ) in  hi IRQ ACTIVE LOW
 gpio-156 (                    |Button Y            ) in  hi IRQ ACTIVE LOW
 gpio-157 (                    |Button A            ) in  hi IRQ ACTIVE LOW

gpiochip5: GPIOs 160-191, parent: platform/10010000.pin-controller, GPIOF:
 gpio-163 (                    |enable              ) out hi ACTIVE LOW
 gpio-170 (                    |R2 shoulder button  ) in  hi IRQ ACTIVE LOW
 gpio-180 (                    |enable              ) out lo
 gpio-181 (                    |Headphone detection ) in  hi IRQ
pocketgo2:/ $

```

**Comment by esmith13** [comment]
Also note that when using pg2test_pg2v2.opk on the customized image, it detects an analog is present (shows it graphically) and registers movement of the analog. Also, menu button is properly identified as MENU (RCTRL) instead of registering as Power Button .
Analog works in menus and all apps as expected.
Below is dmesg output from customized image as well in case it helps:

```
PocketGo2:~ $ dmesg
[    0.000000] Linux version 5.14.0-rc7-opendingux (ninoh-fox@debian) (mipsel-gcw0-linux-uclibc-gcc.br_real (Buildroot od-rs90-2020.10.04-3208-g489d3a790c-dirty) 10.2.0, GNU ld (GNU Binutils) 2.35.2) #2 Sun Aug 29 09:38:24 CEST 2021
[    0.000000] CPU0 revision is: 2ed1024f (Ingenic XBurst)
[    0.000000] FPU revision is: 00330000
[    0.000000] MIPS: machine is wolsen PocketGo2
[    0.000000] earlycon: jz4770_uart0 at MMIO 0x10032000 (options '57600n8')
[    0.000000] printk: bootconsole [jz4770_uart0] enabled
[    0.000000] User-defined physical RAM map overwrite
[    0.000000] cma: Reserved 16 MiB at 0x00c00000
[    0.000000] Primary instruction cache 16kB, VIVT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 16kB, 4-way, VIPT, no aliases, linesize 32 bytes
[    0.000000] MIPS secondary cache 256kB, 4-way, linesize 128 bytes.
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000]   HighMem  [mem 0x0000000010000000-0x000000003fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000]   node   0: [mem 0x0000000030000000-0x000000003fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000003fffffff]
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 130560
[    0.000000] Kernel command line: mem=0x0100M mem=0x0100M@0x30000000 root=/dev/loop0 root=/dev/mmcblk0p1 rootfstype=vfat rootwait ro init=/sbin/init init=/mininit-syspart console=ttyS2,57600 earlycon console=tty0 splash rfkill.default_state=0 -- hwvariant=v20_mddr_512mb
[    0.000000] Unknown command line parameters: splash
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 489848K/524288K available (6025K kernel code, 832K rwdata, 1136K rodata, 1276K init, 255K bss, 18056K reserved, 16384K cma-reserved, 262144K highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] trace event string verifier disabled
[    0.000000] NR_IRQS: 256
[    0.000000] random: get_random_bytes called from start_kernel+0x500/0x6ac with crng_init=0
[    0.000000] clocksource: ingenic-timer: mask: 0xffff max_cycles: 0xffff, max_idle_ns: 38884100 ns
[    0.000002] sched_clock: 16 bits at 750kHz, resolution 1333ns, wraps every 43690000ns
[    0.013674] Console: colour dummy device 80x25
[    0.019877] printk: console [tty0] enabled
[    0.025524] printk: bootconsole [jz4770_uart0] disabled
[    0.033507] Calibrating delay loop... 995.82 BogoMIPS (lpj=20733952)
[    0.167035] pid_max: default: 32768 minimum: 301
[    0.167194] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.167227] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.168595] Performance counters: No available PMU.
[    0.169113] devtmpfs: initialized
[    0.175718] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635852588028829 ns
[    0.175779] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.176631] pinctrl core: initialized pinctrl subsystem
[    0.177677] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.178479] thermal_sys: Registered thermal governor 'step_wise'
[    0.196163] platform 13080000.ipu: Fixing up cyclic dependency with 13050000.lcd-controller
[    0.200546] platform connector: Fixing up cyclic dependency with 13440000.usb
[    0.201611] platform panel: Fixing up cyclic dependency with 13050000.lcd-controller
[    0.205433] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    0.213702] jz4780-dma 13420000.dma-controller: JZ4780 DMA controller initialised
[    0.214427] jz4780-dma 13420100.dma-controller: JZ4780 DMA controller initialised
[    0.215479] mmc1_vcc: supplied by vcc
[    0.216030] gpio-101 (sda): enforced open drain please flag it properly in DT/ACPI DSDT/board file
[    0.216091] gpio-100 (scl): enforced open drain please flag it properly in DT/ACPI DSDT/board file
[    0.216762] i2c-gpio i2c-controller@3: using lines 101 (SDA) and 100 (SCL)
[    0.217409] Advanced Linux Sound Architecture Driver Initialized.
[    0.218582] clocksource: Switched to clocksource ingenic-timer
[    0.271786] NET: Registered PF_INET protocol family
[    0.272030] IP idents hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.272757] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.272850] TCP established hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.272939] TCP bind hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.273029] TCP: Hash tables configured (established 2048 bind 2048)
[    0.273219] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.273295] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.273503] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.274510] Initialise system trusted keyrings
[    0.274822] workingset: timestamp_bits=30 max_order=17 bucket_order=0
[    0.279610] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.472802] Key type asymmetric registered
[    0.472862] Asymmetric key parser 'x509' registered
[    0.475575] DCDC1: supplied by regulator-dummy
[    0.476255] DCDC2: supplied by regulator-dummy
[    0.476902] DCDC3: supplied by regulator-dummy
[    0.477477] SUDCDC_REG4: Bringing 5000000uV into 5300000-5300000uV
[    0.480882] LDO5: supplied by vcc
[    0.481973] LDO6: supplied by vcc
[    0.482554] LDO7: Bringing 1200000uV into 3300000-3300000uV
[    0.484973] LDO7: supplied by vcc
[    0.485531] LDO8: supplied by vcc
[    0.545253] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    0.547243] printk: console [ttyS2] disabled
[    0.547390] 10032000.serial: ttyS2 at MMIO 0x10032000 (irq = 9, base_baud = 750000) is a 16550A
[    1.405643] printk: console [ttyS2] enabled
[    1.413350] ingenic-drm 13050000.lcd-controller: bound 13080000.ipu (ops 0x807a400c)
[    1.434903] etnaviv etnaviv: bound 13040000.gpu (ops 0x807b4ae4)
[    1.444362] etnaviv-gpu 13040000.gpu: model: GC860, revision: 4621
[    1.454822] [drm] Initialized etnaviv 1.3.0 20151214 for etnaviv on minor 0
[    1.466534] loop: module loaded
[    1.470614] nt39016@0 enforce active low on chipselect handle
[    1.485291] input: pwm-vibrator as /devices/platform/rumble/input/input0
[    1.497967] jz4740-rtc 10003000.rtc: registered as rtc0
[    1.505874] jz4740-rtc 10003000.rtc: setting system clock to 2021-09-01T14:48:24 UTC (1630507704)
[    1.521581] jz4780-i2c 10051000.i2c-controller: Bus frequency is 100 KHz
[    1.536537] clocksource: ingenic-ost: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 159271703898 ns
[    1.553925] jz4740-mmc 10022000.mmc: Got CD GPIO
[    1.563137] clocksource: Switched to clocksource ingenic-ost
[    1.571890] sched_clock: 32 bits at 12MHz, resolution 83ns, wraps every 178956970966ns
[    1.589828] iio-rescale voltage-divider: using raw+scale source channel
[    1.600564] jz4740-mmc 10021000.mmc: Ingenic SD/MMC card driver registered
[    1.611713] jz4740-mmc 10021000.mmc: Using DMA, 4-bit mode
[    1.623727] jz4740-mmc 10022000.mmc: Ingenic SD/MMC card driver registered
[    1.634920] jz4740-mmc 10022000.mmc: Using DMA, 4-bit mode
[    1.643682] NET: Registered PF_INET6 protocol family
[    1.652313] Segment Routing with IPv6
[    1.657282] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    1.667392] NET: Registered PF_PACKET protocol family
[    1.675358] Loading compiled-in X.509 certificates
[    1.688499] ingenic-drm 13050000.lcd-controller: bound 13080000.ipu (ops 0x807a400c)
[    1.702271] [drm] Initialized ingenic-drm 1.1.0 20200716 for 13050000.lcd-controller on minor 1
[    1.735748] random: fast init done
[    1.742255] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.745138] mmc0: new high speed SDHC card at address e624
[    1.746474] mmcblk0: mmc0:e624 SB16G 14.8 GiB
[    1.749424]  mmcblk0: p1 p2
[    1.755039] mmc1: host does not support reading read-only switch, assuming write-enable
[    1.757092] mmc1: new high speed SDHC card at address b368
[    1.758344] mmcblk1: mmc1:b368 CBADS 30.0 GiB
[    1.759778]  mmcblk1: p1
[    1.773115] Console: switching to colour frame buffer device 53x24
[    1.890357] ingenic-drm 13050000.lcd-controller: [drm] fb0: ingenic-drm frame buffer device
[    1.909972] usb-conn-gpio connector: repeated role: none
[    1.919996] input: joystick as /devices/platform/joystick/input/input1
[    1.943709] input: gcw0-audio Headphones as /devices/platform/sound/sound/card0/input2
[    1.963194] input: gpio-keys as /devices/platform/gpio-keys/input/input3
[    1.979161] ALSA device list:
[    1.983841]   #0: gcw0-audio
[    1.995881] VFS: Mounted root (vfat filesystem) readonly on device 179:1.
[    2.016742] devtmpfs: mounted
[    2.028197] Freeing unused kernel image (initmem) memory: 1276K
[    2.038836] This architecture does not have kernel memory protection.
[    2.052900] Run /mininit-syspart as init process
[    2.060870]   with arguments:
[    2.060882]     /mininit-syspart
[    2.060888]     splash
[    2.060893]     hwvariant=v20_mddr_512mb
[    2.060898]   with environment:
[    2.060903]     HOME=/
[    2.060908]     TERM=linux
[    2.067704] process '/mininit-syspart' started with executable stack
[    2.083968] mininit: OpenDingux mininit 2.0.2
[    2.094490] loop0: detected capacity change from 0 to 152720
[    2.164296] mininit: rootfs.squashfs mounted on /root
[    2.182574] mininit: root switch done
[    2.199666] mininit: starting /sbin/init
[    2.842568] loop1: detected capacity change from 0 to 4720
[    2.852599] /dev/loop1: Can't open blockdev
[    3.386278] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null). Quota mode: disabled.
[    3.403889] ext4 filesystem being mounted at /media/data supports timestamps until 2038 (0x7fffffff)
[    3.771650] udevd[176]: starting version 3.2.9
[    3.785707] random: udevd: uninitialized urandom read (16 bytes read)
[    3.796205] random: udevd: uninitialized urandom read (16 bytes read)
[    3.808133] random: udevd: uninitialized urandom read (16 bytes read)
[    3.869025] udevd[177]: starting eudev-3.2.9
[    4.381639] remoteproc remoteproc0: ingenic-vpu is available
[    4.628544] usbcore: registered new interface driver usbfs
[    4.731229] usbcore: registered new interface driver hub
[    4.739354] usbcore: registered new device driver usb
[    4.850025] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.909075] ohci-platform: OHCI generic platform driver
[    4.917189] ohci-platform 13430000.usb: Generic Platform OHCI controller
[    5.036799] ohci-platform 13430000.usb: new USB bus registered, assigned bus number 1
[    5.050004] ohci-platform 13430000.usb: irq 20, io mem 0x13430000
[    5.206434] urandom_read: 3 callbacks suppressed
[    5.206455] random: blkid: uninitialized urandom read (6 bytes read)
[    5.243813] usb usb1: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 5.14
[    5.257765] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    5.269632] usb usb1: Product: Generic Platform OHCI controller
[    5.278850] usb usb1: Manufacturer: Linux 5.14.0-rc7-opendingux ohci_hcd
[    5.289627] usb usb1: SerialNumber: 13430000.usb
[    5.399183] hub 1-0:1.0: USB hub found
[    5.431576] hub 1-0:1.0: 2 ports detected
[    5.536148] squashfs: Unknown parameter 'utf8'
[    5.693725] random: crng init done
[    6.590864] file system registered
[    6.595193] using random self ethernet address
[    6.601452] using random host ethernet address
[    6.607772] using random self ethernet address
[    6.614030] using random host ethernet address
[    6.631458] usb0: HOST MAC 76:b6:98:9f:80:ef
[    6.646497] usb0: MAC 66:5f:33:94:05:cc
[    6.884872] IPv6: ADDRCONF(NETDEV_CHANGE): usb0: link becomes ready
[    7.274335] input: OpenDingux mouse daemon as /devices/virtual/input/input4
[    7.664215] Console: switching to colour dummy device 80x25
[   28.078413] Console: switching to colour frame buffer device 53x24
[   28.174737] unloading
[   30.930806] file system registered
[   30.930874] using random self ethernet address
[   30.930885] using random host ethernet address
[   30.930935] using random self ethernet address
[   30.930946] using random host ethernet address
[   30.943470] usb0: HOST MAC 16:c3:74:38:1e:4a
[   30.943552] usb0: MAC 5e:84:00:1f:06:b5
[   31.175306] IPv6: ADDRCONF(NETDEV_CHANGE): usb0: link becomes ready
[   32.113925] Console: switching to colour dummy device 80x25
[   33.345399] LDO_REG10: disabling
[  177.463728] loop2: detected capacity change from 0 to 1880
PocketGo2:~ $
```

**Comment by pcercuei** [comment]
Thanks, that's helpful.

The MENU button is properly identified as the "menu" button on OpenDingux (KEY_HOME), which is the same key code that's injected by the power button, yes. Not a bug.

**Comment by Ninoh-FOX** [comment]
> Thanks, that's helpful.
> 
> The MENU button is properly identified as the "menu" button on OpenDingux (KEY_HOME), which is the same key code that's injected by the power button, yes. Not a bug.

That is true, I need rename the keys in the tester for odbeta, but is how @pcercuei said, the keys works fine.

**Comment by esmith13** [comment]
@Ninoh-FOX I just mentioned it because although your tester shows home key for both power and menu, with your files the picture in the tester highlights power for power and home for home. With clean ODBeta the picture highlights power for both power and menu buttons.
I guess you somehow tag each button in your files independently of the actual keystroke so your tester can identify them?

**Comment by Stories8106** [comment]
I am also having issues with the analog stick.  It's detecting, but registering slightly up and to the left of center, resulting in unplayable emulation.

**Comment by eduardofilo** [comment]
Could someone with a PG v1 try to boot with this image, please?

https://drive.google.com/file/d/1KWllYkJEjpbFoBE3AQzdklxA_vLsGfWM/view?usp=sharing

**Comment by NickMellon** [comment]
> 
> 
> Could someone with a PG v1 try to boot with this image, please?
> 
> https://drive.google.com/file/d/1KWllYkJEjpbFoBE3AQzdklxA_vLsGfWM/view?usp=sharing

It boots. I haven't put any games over yet, but I've noticed a couple of issues:
I can't get it to shutdown. Shutdown and Reboot both do the same thing (reboot) and Quit takes me to the stock launcher. 
I can't find a brightness control, I had to use the stock UI to change the brightness. I'll copy some games over and test in a bit.

**Comment by eduardofilo** [comment]
Thanks. In that case we will wait for the solution to be provided upstream.

**Comment by esmith13** [comment]
@eduardofilo For the sake of completeness:

Your latest image (v1.2e) boots and operates fine in general.
Shutdown works if you correct the system clock via gmenu2x first. It reboots instead of shutting down if the year is drastically off in either direction.
Brightness was barely visible on first boot. Easily fixed by exiting to gmenu2x and using the power+DPad shortcut for brightness.
Analog stick is not recognized, but as with previous images, using @Ninoh-FOX boot files instead of what is included with your image the analog works fine.
Image seems very stable after a few hours of play, regardless of which boot files are used. I am quite impressed with how the PG2v1 performs with your software!

**Comment by eduardofilo** [comment]
Well, thanks for the compliments, although it's not my software but my software mix, you know. :-)

**Comment by esmith13** [comment]
@eduardofilo   FYI - Yesterday's (07.09.21) nightly build of ODBeta fixed the analog stick!!! Shutdown worked first try as well!

**Comment by Ninoh-FOX** [comment]
> @eduardofilo FYI - Yesterday's (07.09.21) nightly build of ODBeta fixed the analog stick!!! Shutdown worked first try as well!
> http://od.abstraction.se/opendingux/latest/gcw0-update-2021-09-07.opk

Nice

**Comment by eduardofilo** [comment]
Very nice. @esmith13 (or anyone who is in a position to test it), can you try this new version?

https://drive.google.com/file/d/1LoCm89TS7yTIo0zqZWmSaP24IieBjL8U/view?usp=sharing

**Comment by esmith13** [comment]
> Very nice. @esmith13 (or anyone who is in a position to test it), can you try this new version, please?
> 
> https://drive.google.com/file/d/1LoCm89TS7yTIo0zqZWmSaP24IieBjL8U/view?usp=sharing

PERFECT! Thank you soooo much!!

only issues I can find are quirks in the release of ODBeta for this device:
1) won't shutdown properly unless date/time are "reasonably accurate"
2) brightness starts off barely visible on first boot (Power+DPad-Right fixes it)
3) volume steps are: off, loud, louder, louder2, louder3, obnoxious, speaker-rattling (lol)

**Comment by pcercuei** [comment]
@esmith13 the "won't shutdown properly" bug still happens?

**Comment by esmith13** [comment]
> @esmith13 the "won't shutdown properly" bug still happens?

ONLY if the year on the clock is VERY wrong. (ex: 1970 or 2056)
If you pull the battery from a PG2v1 and/or let it run completely flat and it remains that way long enough the RTC will lose the correct date/time. If the year is drastically off, it reboots when you try to shutdown. Once you fix it via the clock app, it will shutdown correctly every time unless the date becomes extremely incorrect again.
Honestly I wouldn't be surprised if it's a hardware or firmware issue that can't be fixed in software.
It only really comes up when you have an OS that won't boot correctly. When you power on the PG2v1 if the OS won't work, the power LED doesn't come on and you don't realize it but the device begins draining battery until it's flat even though it looks as if it never actually turned on in the first place.

**Comment by pcercuei** [comment]
@esmith13 and did you try that with the very latest beta?

**Comment by esmith13** [comment]
I have two devices: a PlayGo v1 and a PG2 v1. I flashed a SD card with the Miyoo FW for each and updated both to ODBeta 20210907. One of them was properly shutdown previously and had a full charge. The other had suffered a failed boot previous to this testing and the battery was completely flat. The charged device shutdown correctly first try. The flat device rebooted instead of shutting down. Once it came back up, knowing the issue, I fixed the date/time and shut it down again which worked correctly. 
The only thing I haven't consciously tested is if the stock Miyoo FW has the same issue, solidifying it as a hardware/firmware problem.
I can do that if you would like?

**Comment by pcercuei** [comment]
@esmith13 update them both to the latest OD beta, then take out the batteries of both, re-insert them, boot them, try to power off.

**Comment by esmith13** [comment]
Both devices exhibit the same behavior. 
After pulling battery for 10 seconds and re-inserting, device reboots instead of doing a shutdown until the clock is corrected, after which, shutdown works correctly. 
On both devices I tried multiple shutdowns before fixing clock to make sure it wasn't just an error on first boot after the update. They always rebooted instead of shutting down when the clock was in its reset state of 1970-01-01 00:00

As a side note, I tried Miyoo OFW with the battery pulled just for a comparison and surprisingly, it correctly shutdown even when the clock was reset to default after pulling the battery for 10 seconds.

**Comment by Ninoh-FOX** [comment]
I was the same problem in ROGUE with PG2V1/V2, but now works fine. Anyway, putout the battery in beta, insert the sdcard in the pc and erase the folther /data, then wait that beta finish the first boot and try if poweroff works fine in the last release.

**Comment by pcercuei** [comment]
@esmith13 a guy on discord has problems with OD beta on his PG2v2, he said:
"The Left button (L2) is registering as L1. Volume still doesn't work, and the analog is still not tracking correctly. The analog tracking makes all the emulators useless. Also the OS crashes randomly."

Do you have these issues too?

**Comment by esmith13** [comment]
@pcercuei I did not have those issues on ODbeta released Sept.7th. I have not tried newer. My device is at my office so I cannot test newer releases until Monday but would be happy to then. Is there somewhere else you would like me to post my results on Monday that is more appropriate or useful for ODbeta specific support/issues than here? I don't mind helping with regular testing going forward if it would be useful to you.

**Comment by esmith13** [comment]
@pcercuei Sept.27th build for PG2v1 worked great for me. Sound was off by default and tapping VOL+ one time goes from zero to LOUD, but vol controls do work. Analog stick worked good enough for me to do special moves in Street Fighter Alpha 3 on PS1. Only test I could think of for L1/L2 was to use the input test app and it did register both as their individual and correct inputs (Tab and PgDn if i remember correctly). I did just notice you said the person has a PG2v2 - which I don't have. My PG2 and PlayGo are both v1.

**Comment by pcercuei** [comment]
Ok, I thought you had a PG2v2 too.

**Comment by Stories8106** [comment]
I have a PG2v2 if you want me to test anything.

**Comment by ridsama** [comment]
> @esmith13 a guy on discord has problems with OD beta on his PG2v2, he said: "The Left button (L2) is registering as L1. Volume still doesn't work, and the analog is still not tracking correctly. The analog tracking makes all the emulators useless. Also the OS crashes randomly."
> 
> Do you have these issues too?

I have Powkiddy Q80, clone of PlayGo and PGo2 V2. I do have the issue with L1 and L2 being swapped if I use PGo2 V2 kernel from the Adam 1.2 image. If I use RG350 image, all buttons work but no menu/home button (because RG350 doesn't have it). The joystick is not at neutral position. I have to move to left-up to get it to neutral in testing app. Volume goes from off to loud as mentioned by others too. If there's anything you want me to test, I'm also open.

**Comment by ReiMasa** [comment]
This issue persists on adam_v1.3_PGv1.img.xz from the release page released 16 days ago from this post. Cannot get my PGo2 V1 (no reset button) to boot with the adam image

**Comment by esmith13** [comment]
> This issue persists on adam_v1.3_PGv1.img.xz from the release page released 16 days ago from this post. Cannot get my PGo2 V1 (no reset button) to boot with the adam image. I cannot get it to boot with the v1.2 ones in this comment chain either. I have no problems getting my PGo2V1 to boot with Rogue CFW using the methods to make sure it's working (removing battery etc)

Odd, I updated both of my v1 devices and the booted right away. You sure it's a v1? Have you tried using the normal image as if it was a v2? What utility do you flash the image with to the sd card? What size/brand sd card are you using and did rogue cfw work with exact same sd card?

**Comment by ReiMasa** [comment]
> > This issue persists on adam_v1.3_PGv1.img.xz from the release page released 16 days ago from this post. Cannot get my PGo2 V1 (no reset button) to boot with the adam image. I cannot get it to boot with the v1.2 ones in this comment chain either. I have no problems getting my PGo2V1 to boot with Rogue CFW using the methods to make sure it's working (removing battery etc)
> 
> Odd, I updated both of my v1 devices and the booted right away. You sure it's a v1? Have you tried using the normal image as if it was a v2? What utility do you flash the image with to the sd card? What size/brand sd card are you using and did rogue cfw work with exact same sd card?

Yes, I have no reset button and it's a PocketGo2V1 for sure as I also reinstalled Rogue CFW a day ago from V1 file for it too. 
I have not tried the normal image, but Ill give it a shot. I used Win32Imager for both CFWs and Rogue works fine. I had problems with Balena Etcher pseudo-bricking the sd card but I will try it again since I have it in working state. Sandisk 32gb that i've done multiple formats of Rogue CFW at this point onto it that have worked, yep. I'll try the other things I haven't tried that you listed.

**Comment by esmith13** [comment]
So, it works in the pg2v1 now but crashes the pc?
Do you have any software loaded on your pc that lets you work with Linux file systems? If so, disable it and then try putting the sd card in your pc again. As for etcher, go into its settings and try turning on the eject when complete option to help with the crashing.

**Comment by eduardofilo** [comment]
@ReiMasa, you will have to found alternatives, although what you describe implies problems in your PC system or hardware. You can decompress the .img.xz file with [7-zip](https://www.7-zip.org/) for instance, and then flash with [Win32DiskImager](https://sourceforge.net/projects/win32diskimager/).

@esmith13 Do you think we can close this issue? You know that I do not have the machine, so I depend on the tests that those of you who have it can do to consider it closed. Thanks...

**Comment by esmith13** [comment]
Well, clean installs of v1.3.1 on both of my PG2v1 devices and we're back to not being able to shutdown. A shutdown causes a reboot everytime, regardless of having correctly set the clock or not. Clean flashed back to an older version (v1.2) work as expected. Flashing yet again to 1.3.1 reboots instead of shutting down again.

**Comment by eduardofilo** [comment]
Try with last ODbeta build to see if the situation changes:
http://od.abstraction.se/opendingux/latest/gcw0-update-2021-11-25.opk
I have observed that behaviour in my RG280V after entering/leaving several times from sleep mode, and the solution in my case is to press reset just after the system closes (or just before the boot begins). I suppose the reset would work at any time, but I use it in that way to minimize file system corruption. Surely it will not be the same as in your console, given the precedents of this problem in your machine and since you do not speak of entering/leaving suspension.

**Comment by eduardofilo** [comment]
If the upgrade do not improve things and if you say that version 1.2 of the image does not give you that problem, then it may be better to do downgrade to the ODbeta version installed in that version of the image, that is, 2021-09-07.

http://od.abstraction.se/opendingux/319ec451b854baeb66bd02f35ea19d3453c9fb17/gcw0-update-2021-09-07.opk

**Comment by esmith13** [comment]
> Try with last ODbeta build to see if the situation changes: http://od.abstraction.se/opendingux/latest/gcw0-update-2021-11-25.opk ...

I have tried flashing stock FW and updating to ODBeta 2021-11-25. It worked flawlessly on the first try. Didn't matter if I set the clock or not. powered off and on multiple times even tried pulling battery and reinserting. It always properly shutdown.

Is it possible than manually installing ODBeta as I just did yields different results in some small way than flashing an image that is already ODBeta? Is it possible that for this hardware it isn't going to work unless it's manually build per device?

I'm going to try taking an image of my now ODBeta upgraded SD card and writing it back to another SD card and see what happens. Also, I could upload a copy of that image to a GDrive for you to grab if it helps in any way.

**Comment by eduardofilo** [comment]
Have you tried updating Adam to the latest build of ODbeta (2021-11-25)?

Please also tell me if you had this problem with Adam version 1.3 (not 1.3.1). 

I don't think the installation method (flashing image or running OPK update) differs, but it is only my user level opinion.

Please, try also upgrading to 2021-10-15 ODbeta (which is the one installed by default in Adam 1.3 and 1.3.1) over a stock clean installation. That way we will know that the installation method influences that issue or that perhaps there is something in Adam's configuration that is interfering, although it will be difficult to distinguish between the two scenarios.

http://od.abstraction.se/opendingux/07189457da1c6ecf153b945a96d30785e985e135/gcw0-update-2021-10-15.opk

But good to know that upgrading to last ODbeta build works well. It will be included in future versions of Adam, or it may be indicated as a workaround to solve this problem on your machine if it is proven that it is related to the installation method (flashing).

As always, thanks for your efforts.

**Comment by esmith13** [comment]
I will do all that but also wanted to add this info:

In any scenario when the Adam Image will not shutdown it can be fixed by doing the following:
1) Pull battery and remove SD1 (Adam Image SD)
2) Insert a SD into SD1 that has stock FW that was upgraded to any version of ODBeta and reinstall battery
3) After ODBeta boots, shutdown (it will stay off correctly)
4) Remove ODBeta SD crad and put Adam Image SD card back in SD1
5) Power on the PG2v1 and Adam Image boots. Shutdown will now properly work.

SOMETHING about a properly created ODBeta SD card will fully correct any Adam Image shutdown problems.
To me this kinda confirms it's a RTC issue on the board and something in the Adam Image (simplemenu??) messes it up and booting a clean ODBeta card can fix it enough to continue using the Adam Image SD card that exhibited the issues.

Does this tell you anything useful?

**Comment by eduardofilo** [comment]
Yes, it sounds like a situation similar to the one I mentioned in my first comment two days ago and that on my machine is solved using RESET. Initially I solved it by changing the card as you say (regardless of what and how it was installed with), but then I found out about the RESET. Try the next time it happens to you.

**Comment by esmith13** [comment]
I can't. The only externally visible hardware difference between the v1 and v2 devices is that we do not have a reset button nor any other way to physically reset the device aside from pulling the battery

**Comment by eduardofilo** [comment]
🤦‍♂️

**Comment by eduardofilo** [comment]
Could you please try this version of the image? I am going to incorporate the support for GCW-Zero in the special version of Adam that is released for PG2v1 since they share bootloader, so I have added the kernel of the last one and the pair of scripts to select between both models in a similar way to how it is done with the different Anbernic models in the normal image. As I do it blindly, I would like to know if after the changes, the image starts on your machine.

https://drive.google.com/file/d/1X3Okjh9RcOJyx5YlM6n26Oz7HTGeCAVm/view?usp=sharing

**Comment by esmith13** [comment]
> Could you please try this version of the image?...

My device isn't with me today. I will definitely try it tomorrow and post the results then. Thank you.

**Comment by esmith13** [comment]
New image worked great, first try. No issues at all.

**Comment by eduardofilo** [comment]
> New image worked great, first try. No issues at all.

Thanks for the test. Just for your info, that 1.4b is the same as 1.3.1 with ODb upgraded to 2021-11-25 and RA upgraded to 2021-12-11.

**Comment by eduardofilo** [comment]
By the way, the problem of reboots when trying to poweroff has gone?

**Comment by esmith13** [comment]
Bonus! Thanks. I'll keep using this new one then.

No reboot issues so far, but I've not pulled the battery for a few minutes to let RTC reset and tried yet. I will do that now and report back in 5-10min.

**Comment by esmith13** [comment]
no good. once clock loses correct settings it won't shut down again. So pulling the battery or allowing it to go completely flat still causes a "reboot instead of shutdown" problem.

**Comment by pcercuei** [comment]
@esmith13 can you compile a custom kernel?

**Comment by esmith13** [comment]
never tried, but with instructions I could most likely do it. I have built other software from source that had step by step instructions available.

**Comment by esmith13** [comment]
As a side note, I booted one time from a factory image that didn't even have ODBeta and then shutdown immediately (without setting clock) and swapped back to my mSD with Adam 1.4b and it booted and shutdown perfectly fine. It is now back to "normal" until such a time when the battery gets pulled or goes flat again.

**Comment by pcercuei** [comment]
Chances are that OD beta nightlies before July worked fine too.

**Comment by esmith13** [comment]
even the 2021-11-25 ODBeta nightly worked to "fix" the issue (by booting a separate card with stock FW updated to ODBeta). This was just the first time I tried without ODBeta at all.
It seems stock works, most of not all ODBeta's work, but for some reason ADAM has the issue even though it's built on top of those.

**Comment by pcercuei** [comment]
So you are saying that this bug does not happen if running vanilla OD beta?
Could you double-check that?

**Comment by esmith13** [comment]
sure. which nightly do you want me to use?

**Comment by pcercuei** [comment]
Latest, I guess

**Comment by esmith13** [comment]
You are correct, my apologies. ODBeta (latest) exhibits the same shutdown problem after a pulled battery. Only stock/factory image fixes the shutdown problem.

**Comment by pcercuei** [comment]
Try with this build from April 2021 then:
http://od.abstraction.se/opendingux/4cfcd56c0b9f5730d6c1a54ac6d02b405fe2beb4/

**Comment by esmith13** [comment]
The April 2021 build will not shutdown properly either. 
If it matters it also has the garbled olive green graphics (but I was able to find the "Power Off" setting to try proper shutdown).

**Comment by esmith13** [comment]
For anyone that comes here from the other Issue #125 thread, here's the only "easy" fix at the moment:

Download the stock firmware for the PG2v1 from here:   [https://github.com/retrogamehandheld/PocketGo2/wiki/Firmware-and-software-updates](https://github.com/retrogamehandheld/PocketGo2/wiki/Firmware-and-software-updates)
Write it to a spare mSD card and boot your device with it once then shutdown properly (it will stay off as expected).
Swap back to your ADAM image mSD card and resume normal use.
You should be good as long as you don't completely re-flash your ADAM Image mSD card from scratch, pull out your battery, or allow your battery to drain completely. If any of those does happen, just boot from the stock image once to fix the issue again.
Rinse and repeat.

**Comment by eduardofilo** [comment]
Thanks @esmith13 . I am going to translate your workaround to the `Problem solving` section.

**Comment by eduardofilo** [comment]
Can this issue be considered solved? That is to say, is the support for v1 of these consoles correct enough?

**Comment by esmith13** [comment]
> Can this issue be considered solved? That is to say, is the support for v1 of these consoles correct enough?

I think that would be fair enough to say.
While it would be nice to not need the workaround for the shutdown issue, the v2 device is way more predominant and the only model still available for purchase. Getting any further resolution would seem an unreasonable ask to me.

**Comment by eduardofilo** [comment]
Thanks @esmith13.
